---
platform: linux
image_resource: 
  type: docker-image
  source: 
    repository: tmobilecf/tmo-concourse-ubuntu

inputs:
- name: cf-smoke-tests

run:
  path: sh
  args:
  - -exc
  - |
    python pcf-smoke-tests/src/deploy_smoke_tests.py
